### ISSUE TITLE
MADDPG实现相关

### ISSUE THREAD

**Issue by Ann2cb** [Daniel-ChenJH/CSMA-CA-simulation-and-RL-enhancement#1]
您好，想请问一下CSMA/CA实现MADDPG算法时，有关多智能体的代码，是在main.py中构建多智能体（多个node）吗？还是需要在agent.py中重新定义类呢？谢谢！

**Comment by Daniel-ChenJH** [comment]
你好，可以参考final report中对应部分的说明，在main.py里面定义多个node即可。
```
为了充分与CSMA/CA协议适配，我们将每一个node定义为一个智能体，CSMA/CA协议中node.py文件中的函数封装为智能体的函数，智能体的状态与动作的定义如5.1节中所述。

```

**Comment by Ann2cb** [comment]
> 你好，可以参考final report中对应部分的说明，在 main.py 定义多个node即可。
> 
> ```
> 为了充分与CSMA/CA协议适配，我们将每一个node定义为一个智能体，CSMA/CA协议中node.py文件中的函数封装为智能体的函数，智能体的状态与动作的定义如5.1节中所述。
> ```

谢谢回复！还想请教一下你们的代码主要仿真的是训练过程，为什么没有考虑模型test阶段呢？

**Comment by Daniel-ChenJH** [comment]
> > 你好，可以参考final report中对应部分的说明，在 main.py 定义多个node即可。
> > ```
> > 为了充分与CSMA/CA协议适配，我们将每一个node定义为一个智能体，CSMA/CA协议中node.py文件中的函数封装为智能体的函数，智能体的状态与动作的定义如5.1节中所述。
> > ```
> 
> 谢谢回复！还想请教一下你们的代码主要仿真的是训练过程，为什么没有考虑模型test阶段呢？

主要是这个项目当时是强化学习在CSMA CA协议应用初探，作为限时的课程大作业，我们就只做了适配性接入和训练，而没有后面的其他阶段。如果感兴趣或者本项目对你有帮助的话，你可以fork一版并补充test阶段哈~作者暂时没有继续在做通信协议相关内容的研究了
